### ISSUE TITLE
Can I add aliases to the commands? (Complete beginner to github so I have no idea how this works...)

### ISSUE THREAD

**Issue by chiraggarg03** [amanjha8100/chords#25]
I know how to add it into the code, but I don't know how to work on github to get it done :( (P.S. This is my first issue on github)

**Comment by niloysikdar** [comment]
Hey @chiraggarg03 , can you explain your issue more in detail?

**Comment by chiraggarg03** [comment]
> > Hey @chiraggarg03 , can you explain your issue more in detail?
> 
> From what I understand, he knows how to code, but does not understand how to use Github for pull requests etc.

Yes

**Comment by chiraggarg03** [comment]
For example for _s, I wanted to add another alias (_skip) like the other bots have... Will be easier for users to migrate

**Comment by niloysikdar** [comment]
Sure @chiraggarg03 , that's a nice one, we can definitely add that. So do you want to take this up or we can add this?

**Comment by chiraggarg03** [comment]
@niloysikdar @amanjha8100 @driftywinds Thanks a ton everyone! I've submitted the pull request.
