### ISSUE TITLE
Voting for the playnext command.

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#27]
**Feature**

**Problem Statement**
Currently playnext command adds the song on the top of the queue without constraints. I would like the contributor to implement a voting system with playnext command , where if the votes for the song is greater than 50% of the members in voice , only then will it be moved to the top of the queue, otherwise it will added to the bottom.

**Comment by chmey** [comment]
Yes. I just have to figure out if I need to supply some more intents. Because to get the list of people in private voice channels (=voters) I think I need to grab more permissions.

**Comment by chmey** [comment]
I think that needs the `Intents.members` intent:

> Server Members Intent
> 
> If your bot tracks server members or downloads the entire member list, you may need the server members intent to receive member events and the member list.
>
> NOTE: Once your bot reaches 100 or more servers, this will require Verification and whitelisting. Read more here
