### ISSUE TITLE
Command to show the current playing song.

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#30]
**Feature**

**Problem Statement**
Currently the song being played is not displayed while it is playing. Create the command to add this feature.

**Description**
I would like the contributor to create a function for command to show the current playing song. The expected command is *_cp* .

**Comment by joao-conde** [comment]
@amanjha8100  Can I take this one?

**Comment by joao-conde** [comment]
Just an idea @amanjha8100 , this could be just the current `_q` command (show queue) and at the top you display the currently playing track.

**Comment by joao-conde** [comment]
Honestly, I haven't had the time. But will tackle it today.

**Comment by amanjha8100** [comment]
No problem.
