### ISSUE TITLE
Beautify the readme section.

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#32]
**Design**

**Problem Statement**
The readme right now looks dull and I would want the contributor to beautify the readme section.

**Description**
The contributor is free to come up with ideas or choose whatever tool necessary to improve the readme,

**Comment by amanjha8100** [comment]
Yes you can. Assigning you this @Yoda-Canada .

**Comment by Yoda-Canada** [comment]
@amanjha8100 please review PR, thx.

**Comment by Yoda-Canada** [comment]
@amanjha8100 I have created a new PR, please review it, thx.
