### ISSUE TITLE
Add Vote Skip feature to the current commands.

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#40]
**Problem Statement**
To implement the vote skip feature which will skip a song if 50% of the people in the voice channel vote to skip it.

**Expected Command**
The expected command for the bot is as follows *_voteskip <index>* (1 indexed)

**Comment by amanjha8100** [comment]
Yes you can, @joao-conde !

**Comment by joao-conde** [comment]
I requested more command creation issues because since I will delve into the bot itself and how to create one, I will be on my way to creating more.
