### ISSUE TITLE
Certain commands require roles in discord server, document them, after going through music.py

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#62]
**Documentation**
Certain commands mostly require 'DJ' role. Though already mentioned in readme, document it in a **dedicated** section. Also just add a line of code and explain, how they can add roles.

**Code**
 ```
@commands.has_any_role("DJ")
```
You can just add roles by adding roles in bracket.

**Enhancement**
We can also come up with a programming solution to give bot functionality of adding roles. If you wish to work on that aspect create a new issue.

**Comment by amanjha8100** [comment]
Programming solution is done by @niloysikdar , if anyone else wants to take up the documentation part of it, feel free to go ahead after getting assigned.

**Comment by amanjha8100** [comment]
Hey @EdgarACarneiro , I was a little busy sorry abt that. What I would want is just a small section in readme with details of which command requires 'DJ' roles and the ones who don't. Please note that there are other roles as well but you just need to document the DJ ones.

**Comment by EdgarACarneiro** [comment]
What do you think of something in this format?

| Command | DJ  |
|:-|:-:|
| command_A | |
| command_B | :white_check_mark: |

This way if future roles becomes relevant it is just adding new columns and if new commands are added, one just needs to add new rows!

**Comment by amanjha8100** [comment]
Perfect @EdgarACarneiro

**Comment by EdgarACarneiro** [comment]
Sorry @amanjha8100 , it has been a tough couple of days, will take this one today!
