### ISSUE TITLE
The official logo for chords has been selected. Replace the current bot image with the logo.

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#72]
**Documentation**
I would like the contributor to **replace**
 
![image](https://user-images.githubusercontent.com/59255732/136871547-83864e27-a5ef-4a79-913e-4445ccf0b616.png)

with the logo designed for chords.

The logo is situated in **Logo** --> **icon.png**

**Comment by Himanshu664** [comment]
@amanjha8100 I want to work on this issue please assign
