### ISSUE TITLE
Edit the documentation to include the commands presently available!

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#8]
:star:Documentation

**Problem Statement**
Include the present commands of the bot in a dedicated section of the readme.

**Commands Available**
```
        _p : Plays the song with search keyword following the command
        _s : skips the currently playing music
        _q : shows the music added in list/queue
        _l : commands the bot to leave the voice channel
        _help : shows all the commands of the bot.
```

**Comment by niloysikdar** [comment]
Hey @amanjha8100 , I want to work on this. Can you assign me the issue?

**Comment by Souronix44** [comment]
Hey I want to work on this issue I am from GDSC JGEC

**Comment by amanjha8100** [comment]
Hey @Souronix44 , assigned this to you.

**Comment by amanjha8100** [comment]
Hey @Souronix44 with the current latest PRs this issue has been solved. Closing this issue.
