### ISSUE TITLE
command to show total length in minutes of the queue songs!

### ISSUE THREAD

**Issue by amanjha8100** [amanjha8100/chords#90]
**Feature**
I would like the contributor to create a command which will count the number of minutes the songs in queue will take up!

**Comment by rydwhelchel** [comment]
If its alright with you, could I work on this issue?

**Comment by amanjha8100** [comment]
Yes you can @rydwhelchel

**Comment by rydwhelchel** [comment]
Let me know if there's anything I need to check on or change!
